### bcntb.plotly.mclust.R ###
### DESCRIPTION ########################################################
# This script dinamically creates mclust barplots from report file
# generated by the bcntb.mclust.R script

### HISTORY ###########################################################
# Version		Date					Coder						Comments
# 1.0			2017/06/06			Stefano					starting from the scratch

### PARAMETERS #######################################################
current_dir <- getwd()
suppressMessages(library(optparse))
suppressMessages(library(plotly))

##### COMMAND LINE PARAMETERS ###############################################
### Here we take advantage of Optparse to manage arguments####
### Creating list of arguments ###
option_list = list(
  make_option(c("-r", "--report"), action="store", default=NA, type='character',
              help="File containing mclust report (bcntb.mclust.R)"),
  make_option(c("-d", "--dir"), action="store", default=NA, type='character',
              help="Default directory for output")
)

opt = parse_args(OptionParser(option_list=option_list))

# reading mclust report file
mclust <- read.table(opt$report, sep = "\t", header = TRUE, stringsAsFactors = FALSE, row.names = 1)
mclust <- as.data.frame(t(mclust))

# creating stacked barplot for receptor status
r.status <- plot_ly(mclust[-4,],
                    x = rownames(mclust)[-4],
                    y = mclust[-4,]$Neg ,
                    type = 'bar',
                    name = 'Negative',
                    legendgroup="1",
                    # rgba(255,51,51,0.3) --> red
                    # rgba(0,0,204,0.3) --> blue
                    marker = list(color = 'rgba(255,51,51,0.3)',
                                  line = list(color = 'rgba(255,51,51,1)',
                                              width = 1.5)),
                    text = paste(round((mclust$Neg[-4]/rowSums(mclust)[-4])*100, digits = 2),'%'),
                    textpositionsrc = 'center',
                    width = '800px'
            ) %>%
            add_trace(y = mclust[-4,]$Pos,
                      name = 'Positive',
                      legendgroup="1",
                      marker = list(color = 'rgba(0,0,204,0.3)',
                                    line = list(color = 'rgba(0,0,204,1)',
                                                width = 1.5)),
                      text = paste(round((mclust$Pos[-4]/rowSums(mclust)[-4])*100, digits = 2),'%')
            ) %>%
            layout(yaxis = list(title = 'Count'),
                   barmode = 'stack'
            )

# creating stacked barplot for triple negative status

triple.negative <- plot_ly(mclust[4,],
                            x = rownames(mclust)[4],
                            y = mclust[4,]$Neg ,
                            type = 'bar',
                            name = 'No',
                            legendgroup="2",
                             # rgba(102,204,0,0.3) --> light green
                             # rgba(204,0,102,0.3) --> dark pink
                            marker = list(color = 'rgba(102,204,0,0.3)',
                                          line = list(color = 'rgba(102,204,0,1)',
                                                      width = 1.5)),
                            text = paste(round((mclust$Neg[4]/rowSums(mclust)[4])*100, digits = 2),'%'),
                            textpositionsrc = 'center',
                            width = '800px'
                    ) %>%
                    add_trace(y = mclust[4,]$Pos,
                              name = 'Yes',
                              legendgroup="2",
                              marker = list(color = 'rgba(204,0,102,0.3)',
                                            line = list(color = 'rgba(204,0,102,1)',
                                                        width = 1.5)),
                              text = paste(round((mclust$Pos[4]/rowSums(mclust)[4])*100, digits = 2),'%')
                    ) %>%
                    layout(yaxis = list(title = 'Count'), barmode = 'stack')

# merging plots together
mclust.plot <- subplot(r.status, triple.negative, nrows = 1, margin = 0.02, shareY = TRUE)
mclust.plot <- layout(mclust.plot, title="Receptor Status");

## defining plot file name
mclust_filename = paste(opt$dir,"mclust.html",sep = "/")

## saving generated plot into web page
htmlwidgets::saveWidget(mclust.plot, mclust_filename)
